FROM node:20-alpine
WORKDIR /app
COPY backend/package.json backend/package.json
COPY backend/tsconfig.json backend/tsconfig.json
COPY backend/src backend/src
WORKDIR /app/backend
RUN npm install
RUN npm run build
EXPOSE 3001
CMD ["npm", "start"]
